// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDwMTz3nbIrO5PbsKuvESboNf74HmJmeKM',
    appId: '1:998838472353:web:97da005dfc908bdfac6ae0',
    messagingSenderId: '998838472353',
    projectId: 'qucikart1',
    authDomain: 'qucikart1.firebaseapp.com',
    storageBucket: 'qucikart1.appspot.com',
    measurementId: 'G-LLZ8N7J9FL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCCPFq1CY9yoI4ZdIfzQHlfkQVaOCwztro',
    appId: '1:998838472353:android:3cbaa0f579d816c5ac6ae0',
    messagingSenderId: '998838472353',
    projectId: 'qucikart1',
    storageBucket: 'qucikart1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCwumI0vzoiNm7ROhp1xa8B_m4SwKUugKw',
    appId: '1:998838472353:ios:f99045681e7ebc18ac6ae0',
    messagingSenderId: '998838472353',
    projectId: 'qucikart1',
    storageBucket: 'qucikart1.appspot.com',
    iosBundleId: 'com.example.quickartProj',
  );
}
